### ISSUE TITLE
Unused error handling structure (ErrorStack)

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/eae-utils#17]
There is an interesting error handling utility :

https://github.com/dsi-icl/eae-utils/blob/6c072c2b33a04214fb9f52329efcf94c0d6a08e3/src/defines.js#L1-L33

But it is never use anywhere in the code. Instead I see the usage of things like :

https://github.com/dsi-icl/eae-compute/blob/763229207af63cf8cb0aef4d62945b49dd8e2b0a/src/jobExecutorAbstract.js#L81-L110

What is all of that about ?

**Comment by Tezirg** [comment]
Exported from the file here : https://github.com/dsi-icl/eae-utils/blob/6c072c2b33a04214fb9f52329efcf94c0d6a08e3/src/defines.js#L130

**Comment by fguitton** [comment]
Hello Hello @Tezirg !
